version: '3.8'
services:
  app:
    build: .
    container_name: ai-cybersecurity
    ports:
      - "8080"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
